# Generated by Django 5.2.7 on 2025-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100)),
                ('año_compra', models.IntegerField()),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('En reparación', 'En reparación'), ('Dado de baja', 'Dado de baja')], max_length=20)),
            ],
        ),
    ]
